blueprint:
  name: ZHA Remote - Univerzální Ovládání Světel a Scén
  description: >
    Univerzální blueprint pro ZHA dálkový ovladač (např. Ikea STYRBAR E2001/E2002).
    Umožňuje nastavit akce pro single/double/triple klik na horní, spodní, levé a pravé tlačítko
    a také akce při držení tlačítka (hold) pro zvýšení/snížení jasu (horní/dolní) a při držení
    levého/pravého tlačítka (např. změna scény). Volitelně lze při držení provádět změny jen
    na zapnutých světlech.  
    Vše nastavitelné přes UI bez nutnosti psát YAML ručně.

  domain: automation
  input:
    remote:
      name: ZHA Dálkový ovladač
      description: Vyberte zařízení ovladače ZHA.
      selector:
        device:
          integration: zha

    # Nastavení prodlevy pro rozlišení počtu stisků
    wait_time:
      name: Čas pro rozlišení počtu stisků (s)
      description: Doba, během které se čeká na další stisk pro dvojité/trojité kliknutí.
      default: 0.5
      selector:
        number:
          min: 0.1
          max: 2
          step: 0.1
          unit_of_measurement: s

    only_active_lights:
      name: Pouze zapnutá světla při držení (hold)
      description: Pokud je aktivní, hold akce (zvýšení/snížení jasu, změny) se provedou jen na světlech, která jsou zapnutá.
      default: false
      selector:
        boolean: {}

    # Akce pro horní tlačítko (klik)
    single_click_action_top:
      name: Horní tlačítko - jeden klik
      default: []
      selector:
        action: {}
    double_click_action_top:
      name: Horní tlačítko - dvojitý klik
      default: []
      selector:
        action: {}
    triple_click_action_top:
      name: Horní tlačítko - trojitý klik
      default: []
      selector:
        action: {}

    # Akce pro spodní tlačítko (klik)
    single_click_action_bottom:
      name: Spodní tlačítko - jeden klik
      default: []
      selector:
        action: {}
    double_click_action_bottom:
      name: Spodní tlačítko - dvojitý klik
      default: []
      selector:
        action: {}
    triple_click_action_bottom:
      name: Spodní tlačítko - trojitý klik
      default: []
      selector:
        action: {}

    # Akce pro levé tlačítko (klik)
    single_click_action_left:
      name: Levé tlačítko - jeden klik
      default: []
      selector:
        action: {}
    double_click_action_left:
      name: Levé tlačítko - dvojitý klik
      default: []
      selector:
        action: {}
    triple_click_action_left:
      name: Levé tlačítko - trojitý klik
      default: []
      selector:
        action: {}

    # Akce pro pravé tlačítko (klik)
    single_click_action_right:
      name: Pravé tlačítko - jeden klik
      default: []
      selector:
        action: {}
    double_click_action_right:
      name: Pravé tlačítko - dvojitý klik
      default: []
      selector:
        action: {}
    triple_click_action_right:
      name: Pravé tlačítko - trojitý klik
      default: []
      selector:
        action: {}

    # Akce pro držení horního tlačítka (zvýšení jasu)
    hold_increase_top:
      name: Držení horního tlačítka (zvýšení jasu)
      description: Akce, která se provede při držení horního tlačítka pro zvýšení jasu.
      default: []
      selector:
        action: {}

    # Akce pro držení spodního tlačítka (snížení jasu)
    hold_decrease_bottom:
      name: Držení spodního tlačítka (snížení jasu)
      description: Akce, která se provede při držení spodního tlačítka pro snížení jasu.
      default: []
      selector:
        action: {}

    # Akce pro držení levého tlačítka
    hold_left:
      name: Držení levého tlačítka
      description: Akce při držení levého tlačítka (např. změna scény)
      default: []
      selector:
        action: {}

    # Akce pro držení pravého tlačítka
    hold_right:
      name: Držení pravého tlačítka
      description: Akce při držení pravého tlačítka (např. změna scény)
      default: []
      selector:
        action: {}

trigger:
  - platform: event
    event_type: zha_event
    event_data:
      device_id: !input remote

variables:
  command: "{{ trigger.event.data.command }}"
  cluster_id: "{{ trigger.event.data.cluster_id }}"
  endpoint_id: "{{ trigger.event.data.endpoint_id }}"
  args: "{{ trigger.event.data.args }}"

  # Identifikace tlačítka:
  # Předpokládáme Ikea STYRBAR:
  # endpoint_id=1: top (on), bottom (off), hold (move/move_with_on_off)
  # endpoint_id=2: left (on)
  # endpoint_id=3: right (on)
  # hold top/bottom: cluster=8, command=move/move_with_on_off
  # U holdu levého a pravého tlačítka (endpoint 2/3) také cluster 8 a command move/move_with_on_off
  button_name: >
    {% if cluster_id == 6 %}
      {% if endpoint_id == 1 and command == 'on' %}top{% elif endpoint_id == 1 and command == 'off' %}bottom
      {% elif endpoint_id == 2 and command == 'on' %}left{% elif endpoint_id == 3 and command == 'on' %}right
      {% else %}unknown{% endif %}
    {% elif cluster_id == 8 %}
      {% if endpoint_id == 1 and (command == 'move_with_on_off') %}hold_increase_top
      {% elif endpoint_id == 1 and command == 'move' %}hold_decrease_bottom
      {% elif endpoint_id == 2 and (command in ['move','move_with_on_off']) %}hold_left
      {% elif endpoint_id == 3 and (command in ['move','move_with_on_off']) %}hold_right
      {% else %}unknown{% endif %}
    {% else %}
      unknown
    {% endif %}

  is_hold: >
    {{ 'hold' in button_name }}

  is_click: >
    {{ button_name in ['top','bottom','left','right'] }}

  wt: !input wait_time
  only_active: !input only_active_lights

action:
  - choose:
      # HOLD ACTIONS
      - conditions:
          - condition: template
            value_template: "{{ is_hold }}"
        sequence:
          # Podobně jako v původním kódu: pokud only_active = true, provádíme akci jen na zapnutých světlech
          # Zde samotné akce uživatel definuje v input sekci (hold_xxx).
          # Uživatel si v hold_xxx akcích sám vybere světla a v akci může podmínit, že se to aplikuje jen na zapnutá světla.
          # Pokud chceme přímo v blueprintu ošetřit jen zapnutá světla, museli bychom použít templating přímo zde.
          # Pro zjednodušení necháme uživatele definovat akce dle potřeb. Pokud by chtěl jen zapnutá světla,
          # může to udělat pomocí conditions přímo v definované akci.
          - choose:
              - conditions: "{{ button_name == 'hold_increase_top' }}"
                sequence: !input hold_increase_top
              - conditions: "{{ button_name == 'hold_decrease_bottom' }}"
                sequence: !input hold_decrease_bottom
              - conditions: "{{ button_name == 'hold_left' }}"
                sequence: !input hold_left
              - conditions: "{{ button_name == 'hold_right' }}"
                sequence: !input hold_right

      # CLICK ACTIONS
      - conditions:
          - condition: template
            value_template: "{{ is_click }}"
        sequence:
          # Nyní vyřešíme single/double/triple kliky
          - variables:
              this_button: "{{ button_name }}"
              click_count: 1
          - wait_for_trigger:
              - platform: event
                event_type: zha_event
                event_data:
                  device_id: !input remote
            timeout: "{{ wt }}"
            continue_on_timeout: true
          - variables:
              click_count: >
                {% if wait.trigger %}
                  {{ click_count + 1 }}
                {% else %}
                  {{ click_count }}
                {% endif %}
          - wait_for_trigger:
              - platform: event
                event_type: zha_event
                event_data:
                  device_id: !input remote
            timeout: "{{ wt }}"
            continue_on_timeout: true
          - variables:
              click_count: >
                {% if wait.trigger %}
                  {{ click_count + 1 }}
                {% else %}
                  {{ click_count }}
                {% endif %}

          # Podle click_count vybereme akci
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ this_button == 'top' }}"
                sequence:
                  - choose:
                      - conditions: "{{ click_count == 1 }}"
                        sequence: !input single_click_action_top
                      - conditions: "{{ click_count == 2 }}"
                        sequence: !input double_click_action_top
                      - conditions: "{{ click_count == 3 }}"
                        sequence: !input triple_click_action_top

              - conditions:
                  - condition: template
                    value_template: "{{ this_button == 'bottom' }}"
                sequence:
                  - choose:
                      - conditions: "{{ click_count == 1 }}"
                        sequence: !input single_click_action_bottom
                      - conditions: "{{ click_count == 2 }}"
                        sequence: !input double_click_action_bottom
                      - conditions: "{{ click_count == 3 }}"
                        sequence: !input triple_click_action_bottom

              - conditions:
                  - condition: template
                    value_template: "{{ this_button == 'left' }}"
                sequence:
                  - choose:
                      - conditions: "{{ click_count == 1 }}"
                        sequence: !input single_click_action_left
                      - conditions: "{{ click_count == 2 }}"
                        sequence: !input double_click_action_left
                      - conditions: "{{ click_count == 3 }}"
                        sequence: !input triple_click_action_left

              - conditions:
                  - condition: template
                    value_template: "{{ this_button == 'right' }}"
                sequence:
                  - choose:
                      - conditions: "{{ click_count == 1 }}"
                        sequence: !input single_click_action_right
                      - conditions: "{{ click_count == 2 }}"
                        sequence: !input double_click_action_right
                      - conditions: "{{ click_count == 3 }}"
                        sequence: !input triple_click_action_right
    default: []
mode: restart
