blueprint:
  name: ZHA Remote - Universal Control (EN)
  description: >
    A universal blueprint for a ZHA remote (e.g., Ikea STYRBAR E2001/E2002)
    that supports single, double, triple clicks on top, bottom, left, and right buttons,
    as well as hold actions (increase/decrease brightness on top/bottom and custom hold actions on left/right).
    
    Features:
    - Configurable delay to differentiate single/double/triple clicks.
    - Option to apply hold actions for brightness only on currently turned-on lights.
    - Option to apply hold actions for left/right only on currently turned-on lights as well.
  
  domain: automation

  input:
    remote:
      name: ZHA Remote
      description: Select your ZHA remote device.
      selector:
        device:
          integration: zha

    wait_time:
      name: Delay between clicks (seconds)
      description: Time used to differentiate single/double/triple presses.
      default: 0.5
      selector:
        number:
          min: 0.1
          max: 2
          step: 0.1
          unit_of_measurement: s

    only_active_lights_brightness:
      name: Only active lights for brightness hold
      description: If enabled, hold actions for top/bottom (brightness up/down) apply only to currently turned-on lights.
      default: false
      selector:
        boolean: {}

    only_active_lights_scenes:
      name: Only active lights for left/right hold
      description: If enabled, hold actions for left/right apply only to currently turned-on lights.
      default: false
      selector:
        boolean: {}

    # Actions for top button (clicks)
    single_click_action_top:
      name: Top button single click
      default: []
      selector:
        action: {}
    double_click_action_top:
      name: Top button double click
      default: []
      selector:
        action: {}
    triple_click_action_top:
      name: Top button triple click
      default: []
      selector:
        action: {}

    # Actions for bottom button (clicks)
    single_click_action_bottom:
      name: Bottom button single click
      default: []
      selector:
        action: {}
    double_click_action_bottom:
      name: Bottom button double click
      default: []
      selector:
        action: {}
    triple_click_action_bottom:
      name: Bottom button triple click
      default: []
      selector:
        action: {}

    # Actions for left button (clicks)
    single_click_action_left:
      name: Left button single click
      default: []
      selector:
        action: {}
    double_click_action_left:
      name: Left button double click
      default: []
      selector:
        action: {}
    triple_click_action_left:
      name: Left button triple click
      default: []
      selector:
        action: {}

    # Actions for right button (clicks)
    single_click_action_right:
      name: Right button single click
      default: []
      selector:
        action: {}
    double_click_action_right:
      name: Right button double click
      default: []
      selector:
        action: {}
    triple_click_action_right:
      name: Right button triple click
      default: []
      selector:
        action: {}

    # Hold actions
    hold_increase_top:
      name: Hold top (increase brightness)
      default: []
      selector:
        action: {}
    hold_decrease_bottom:
      name: Hold bottom (decrease brightness)
      default: []
      selector:
        action: {}
    hold_left:
      name: Hold left
      default: []
      selector:
        action: {}
    hold_right:
      name: Hold right
      default: []
      selector:
        action: {}

trigger:
  - platform: event
    event_type: zha_event
    event_data:
      device_id: !input remote

variables:
  command: "{{ trigger.event.data.command }}"
  cluster_id: "{{ trigger.event.data.cluster_id }}"
  endpoint_id: "{{ trigger.event.data.endpoint_id }}"
  wt: !input wait_time
  only_brightness: !input only_active_lights_brightness
  only_scenes: !input only_active_lights_scenes

  button_name: >
    {% if cluster_id == 6 %}
      {% if endpoint_id == 1 and command == 'on' %}top{% elif endpoint_id == 1 and command == 'off' %}bottom
      {% elif endpoint_id == 2 and command == 'on' %}left{% elif endpoint_id == 3 and command == 'on' %}right
      {% else %}unknown{% endif %}
    {% elif cluster_id == 8 %}
      {% if endpoint_id == 1 and (command == 'move_with_on_off') %}hold_increase_top
      {% elif endpoint_id == 1 and command == 'move' %}hold_decrease_bottom
      {% elif endpoint_id == 2 and (command in ['move','move_with_on_off']) %}hold_left
      {% elif endpoint_id == 3 and (command in ['move','move_with_on_off']) %}hold_right
      {% else %}unknown{% endif %}
    {% else %}
      unknown
    {% endif %}

  is_hold: >
    {{ 'hold' in button_name }}

  is_click: >
    {{ button_name in ['top','bottom','left','right'] }}

action:
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ is_hold }}"
        sequence:
          # Handle hold actions with optional "only_active" logic
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ button_name == 'hold_increase_top' }}"
                sequence:
                  - choose:
                      - conditions:
                          - condition: template
                            value_template: "{{ only_brightness }}"
                        sequence: !input hold_increase_top
                      - conditions: []
                        sequence: !input hold_increase_top

              - conditions:
                  - condition: template
                    value_template: "{{ button_name == 'hold_decrease_bottom' }}"
                sequence:
                  - choose:
                      - conditions:
                          - condition: template
                            value_template: "{{ only_brightness }}"
                        sequence: !input hold_decrease_bottom
                      - conditions: []
                        sequence: !input hold_decrease_bottom

              - conditions:
                  - condition: template
                    value_template: "{{ button_name == 'hold_left' }}"
                sequence:
                  - choose:
                      - conditions:
                          - condition: template
                            value_template: "{{ only_scenes }}"
                        sequence: !input hold_left
                      - conditions: []
                        sequence: !input hold_left

              - conditions:
                  - condition: template
                    value_template: "{{ button_name == 'hold_right' }}"
                sequence:
                  - choose:
                      - conditions:
                          - condition: template
                            value_template: "{{ only_scenes }}"
                        sequence: !input hold_right
                      - conditions: []
                        sequence: !input hold_right

      - conditions:
          - condition: template
            value_template: "{{ is_click }}"
        sequence:
          - variables:
              this_button: "{{ button_name }}"
              click_count: 1
          # Wait for second click
          - wait_for_trigger:
              - platform: event
                event_type: zha_event
                event_data:
                  device_id: !input remote
            timeout: "{{ wt }}"
            continue_on_timeout: true
          - variables:
              click_count: >
                {% if wait.trigger %}
                  {{ click_count + 1 }}
                {% else %}
                  {{ click_count }}
                {% endif %}
          # Wait for third click
          - wait_for_trigger:
              - platform: event
                event_type: zha_event
                event_data:
                  device_id: !input remote
            timeout: "{{ wt }}"
            continue_on_timeout: true
          - variables:
              click_count: >
                {% if wait.trigger %}
                  {{ click_count + 1 }}
                {% else %}
                  {{ click_count }}
                {% endif %}

          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ this_button == 'top' }}"
                sequence:
                  - choose:
                      - conditions: "{{ click_count == 1 }}"
                        sequence: !input single_click_action_top
                      - conditions: "{{ click_count == 2 }}"
                        sequence: !input double_click_action_top
                      - conditions: "{{ click_count == 3 }}"
                        sequence: !input triple_click_action_top

              - conditions:
                  - condition: template
                    value_template: "{{ this_button == 'bottom' }}"
                sequence:
                  - choose:
                      - conditions: "{{ click_count == 1 }}"
                        sequence: !input single_click_action_bottom
                      - conditions: "{{ click_count == 2 }}"
                        sequence: !input double_click_action_bottom
                      - conditions: "{{ click_count == 3 }}"
                        sequence: !input triple_click_action_bottom

              - conditions:
                  - condition: template
                    value_template: "{{ this_button == 'left' }}"
                sequence:
                  - choose:
                      - conditions: "{{ click_count == 1 }}"
                        sequence: !input single_click_action_left
                      - conditions: "{{ click_count == 2 }}"
                        sequence: !input double_click_action_left
                      - conditions: "{{ click_count == 3 }}"
                        sequence: !input triple_click_action_left

              - conditions:
                  - condition: template
                    value_template: "{{ this_button == 'right' }}"
                sequence:
                  - choose:
                      - conditions: "{{ click_count == 1 }}"
                        sequence: !input single_click_action_right
                      - conditions: "{{ click_count == 2 }}"
                        sequence: !input double_click_action_right
                      - conditions: "{{ click_count == 3 }}"
                        sequence: !input triple_click_action_right
    default: []
mode: restart
