blueprint:
  name: ZHA Remote - Rozšířený ovladač se scénami a barvami
  description: >
    Rozšířený univerzální blueprint pro ZHA dálkový ovladač (např. Ikea STYRBAR E2001/E2002).
    Umožňuje nastavit akce pro single/double/triple klik na horní, spodní, levé a pravé tlačítko
    i akce při držení tlačítka (hold) pro zvýšení/snížení jasu (horní/dolní) a při držení
    levého/pravého tlačítka (např. změna scény).

    Obsahuje možnost ovlivnit, zda se při držení (hold) mají akce aplikovat pouze na zapnutá
    světla, a to zvlášť pro horní/dolní tlačítko (jas) a zvlášť pro levé/pravé tlačítko (scény).

    Navíc můžete přes inputy vybrat konkrétní scény či barvy (např. scény pro levé a pravé tlačítko),
    aniž byste museli psát kód. Barvy lze nastavit přes akce ve výběru (action selector).

  domain: automation
  input:
    remote:
      name: ZHA Dálkový ovladač
      description: Vyberte zařízení ovladače ZHA.
      selector:
        device:
          integration: zha

    wait_time:
      name: Čas pro rozlišení počtu stisků (s)
      description: Doba, během které se čeká na další stisk pro dvojité/trojité kliknutí.
      default: 0.5
      selector:
        number:
          min: 0.1
          max: 2
          step: 0.1
          unit_of_measurement: s

    only_active_lights_brightness:
      name: Pouze zapnutá světla při držení pro jas (top/bottom)
      description: Pokud je aktivní, hold akce na horním/spodním tlačítku se provedou jen na zapnutých světlech.
      default: false
      selector:
        boolean: {}

    only_active_lights_scenes:
      name: Pouze zapnutá světla při držení pro scény (left/right)
      description: Pokud je aktivní, hold akce na levém/pravém tlačítku se provedou jen na zapnutých světlech.
      default: false
      selector:
        boolean: {}

    # Možnost vybrat scény pro levý a pravý tlačítko při jednotlivých kliknutích:
    scene_single_left:
      name: Scéna pro levé tlačítko (single click)
      description: Vyberte scénu, která se aktivuje při jednom stisku levého tlačítka.
      default: []
      selector:
        entity:
          domain: scene

    scene_double_left:
      name: Scéna pro levé tlačítko (double click)
      description: Vyberte scénu, která se aktivuje při dvojím stisku levého tlačítka.
      default: []
      selector:
        entity:
          domain: scene

    scene_triple_left:
      name: Scéna pro levé tlačítko (triple click)
      description: Vyberte scénu, která se aktivuje při trojím stisku levého tlačítka.
      default: []
      selector:
        entity:
          domain: scene

    scene_single_right:
      name: Scéna pro pravé tlačítko (single click)
      description: Vyberte scénu, která se aktivuje při jednom stisku pravého tlačítka.
      default: []
      selector:
        entity:
          domain: scene

    scene_double_right:
      name: Scéna pro pravé tlačítko (double click)
      description: Vyberte scénu, která se aktivuje při dvojím stisku pravého tlačítka.
      default: []
      selector:
        entity:
          domain: scene

    scene_triple_right:
      name: Scéna pro pravé tlačítko (triple click)
      description: Vyberte scénu, která se aktivuje při trojím stisku pravého tlačítka.
      default: []
      selector:
        entity:
          domain: scene

    # Akce pro horní tlačítko (klik)
    single_click_action_top:
      name: Horní tlačítko - jeden klik
      default: []
      selector:
        action: {}
    double_click_action_top:
      name: Horní tlačítko - dvojitý klik
      default: []
      selector:
        action: {}
    triple_click_action_top:
      name: Horní tlačítko - trojitý klik
      default: []
      selector:
        action: {}

    # Akce pro spodní tlačítko (klik)
    single_click_action_bottom:
      name: Spodní tlačítko - jeden klik
      default: []
      selector:
        action: {}
    double_click_action_bottom:
      name: Spodní tlačítko - dvojitý klik
      default: []
      selector:
        action: {}
    triple_click_action_bottom:
      name: Spodní tlačítko - trojitý klik
      default: []
      selector:
        action: {}

    # Akce pro levé tlačítko (klik)
    # Kromě scén lze definovat další akce
    single_click_action_left:
      name: Levé tlačítko - jeden klik (kromě scény)
      description: Zde můžete přidat akci nad rámec nastavené scény.
      default: []
      selector:
        action: {}
    double_click_action_left:
      name: Levé tlačítko - dvojitý klik (kromě scény)
      default: []
      selector:
        action: {}
    triple_click_action_left:
      name: Levé tlačítko - trojitý klik (kromě scény)
      default: []
      selector:
        action: {}

    # Akce pro pravé tlačítko (klik)
    single_click_action_right:
      name: Pravé tlačítko - jeden klik (kromě scény)
      default: []
      selector:
        action: {}
    double_click_action_right:
      name: Pravé tlačítko - dvojitý klik (kromě scény)
      default: []
      selector:
        action: {}
    triple_click_action_right:
      name: Pravé tlačítko - trojitý klik (kromě scény)
      default: []
      selector:
        action: {}

    # Akce pro držení horního tlačítka (zvýšení jasu)
    hold_increase_top:
      name: Držení horního tlačítka (zvýšení jasu)
      default: []
      selector:
        action: {}

    # Akce pro držení spodního tlačítka (snížení jasu)
    hold_decrease_bottom:
      name: Držení spodního tlačítka (snížení jasu)
      default: []
      selector:
        action: {}

    # Akce pro držení levého tlačítka
    hold_left:
      name: Držení levého tlačítka
      default: []
      selector:
        action: {}

    # Akce pro držení pravého tlačítka
    hold_right:
      name: Držení pravého tlačítka
      default: []
      selector:
        action: {}

trigger:
  - platform: event
    event_type: zha_event
    event_data:
      device_id: !input remote

variables:
  command: "{{ trigger.event.data.command }}"
  cluster_id: "{{ trigger.event.data.cluster_id }}"
  endpoint_id: "{{ trigger.event.data.endpoint_id }}"
  args: "{{ trigger.event.data.args }}"
  wt: !input wait_time
  only_brightness: !input only_active_lights_brightness
  only_scenes: !input only_active_lights_scenes

  button_name: >
    {% if cluster_id == 6 %}
      {% if endpoint_id == 1 and command == 'on' %}top{% elif endpoint_id == 1 and command == 'off' %}bottom
      {% elif endpoint_id == 2 and command == 'on' %}left{% elif endpoint_id == 3 and command == 'on' %}right
      {% else %}unknown{% endif %}
    {% elif cluster_id == 8 %}
      {% if endpoint_id == 1 and (command == 'move_with_on_off') %}hold_increase_top
      {% elif endpoint_id == 1 and command == 'move' %}hold_decrease_bottom
      {% elif endpoint_id == 2 and (command in ['move','move_with_on_off']) %}hold_left
      {% elif endpoint_id == 3 and (command in ['move','move_with_on_off']) %}hold_right
      {% else %}unknown{% endif %}
    {% else %}
      unknown
    {% endif %}

  is_hold: >
    {{ 'hold' in button_name }}

  is_click: >
    {{ button_name in ['top','bottom','left','right'] }}

action:
  - choose:
      # HOLD ACTIONS
      - conditions:
          - condition: template
            value_template: "{{ is_hold }}"
        sequence:
          # Pokud byste chtěl opravdu aplikovat držení jen na zapnutá světla, 
          # je potřeba to zajistit v akcích nebo pomocí dodatečných conditions v action.
          # Tento blueprint poskytuje jen boolean, aby jste při definici akce mohl 
          # použít condition: state ... is_on apod.
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ button_name == 'hold_increase_top' }}"
                sequence:
                  # Definujte akce v !input hold_increase_top, uvnitř nich případně podmínky na zapnutá světla
                  - choose:
                      - conditions:
                          - condition: template
                            value_template: "{{ only_brightness }}"
                        sequence: !input hold_increase_top
                      - conditions: []
                        sequence: !input hold_increase_top

              - conditions:
                  - condition: template
                    value_template: "{{ button_name == 'hold_decrease_bottom' }}"
                sequence:
                  - choose:
                      - conditions:
                          - condition: template
                            value_template: "{{ only_brightness }}"
                        sequence: !input hold_decrease_bottom
                      - conditions: []
                        sequence: !input hold_decrease_bottom

              - conditions:
                  - condition: template
                    value_template: "{{ button_name == 'hold_left' }}"
                sequence:
                  - choose:
                      - conditions:
                          - condition: template
                            value_template: "{{ only_scenes }}"
                        sequence: !input hold_left
                      - conditions: []
                        sequence: !input hold_left

              - conditions:
                  - condition: template
                    value_template: "{{ button_name == 'hold_right' }}"
                sequence:
                  - choose:
                      - conditions:
                          - condition: template
                            value_template: "{{ only_scenes }}"
                        sequence: !input hold_right
                      - conditions: []
                        sequence: !input hold_right

      # CLICK ACTIONS
      - conditions:
          - condition: template
            value_template: "{{ is_click }}"
        sequence:
          - variables:
              this_button: "{{ button_name }}"
              click_count: 1
          # Čekání na druhý stisk
          - wait_for_trigger:
              - platform: event
                event_type: zha_event
                event_data:
                  device_id: !input remote
            timeout: "{{ wt }}"
            continue_on_timeout: true
          - variables:
              click_count: >
                {% if wait.trigger %}
                  {{ click_count + 1 }}
                {% else %}
                  {{ click_count }}
                {% endif %}
          # Čekání na třetí stisk
          - wait_for_trigger:
              - platform: event
                event_type: zha_event
                event_data:
                  device_id: !input remote
            timeout: "{{ wt }}"
            continue_on_timeout: true
          - variables:
              click_count: >
                {% if wait.trigger %}
                  {{ click_count + 1 }}
                {% else %}
                  {{ click_count }}
                {% endif %}

          # Aplikace akcí podle počtu stisků
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ this_button == 'top' }}"
                sequence:
                  - choose:
                      - conditions: "{{ click_count == 1 }}"
                        sequence: !input single_click_action_top
                      - conditions: "{{ click_count == 2 }}"
                        sequence: !input double_click_action_top
                      - conditions: "{{ click_count == 3 }}"
                        sequence: !input triple_click_action_top

              - conditions:
                  - condition: template
                    value_template: "{{ this_button == 'bottom' }}"
                sequence:
                  - choose:
                      - conditions: "{{ click_count == 1 }}"
                        sequence: !input single_click_action_bottom
                      - conditions: "{{ click_count == 2 }}"
                        sequence: !input double_click_action_bottom
                      - conditions: "{{ click_count == 3 }}"
                        sequence: !input triple_click_action_bottom

              - conditions:
                  - condition: template
                    value_template: "{{ this_button == 'left' }}"
                sequence:
                  - choose:
                      - conditions: "{{ click_count == 1 }}"
                        sequence:
                          - choose:
                              # Pokud je scéna pro 1x left nastavena
                              - conditions:
                                  - condition: template
                                    value_template: "{{ states('scene_single_left') != 'unknown' and states('scene_single_left') != '' }}"
                                sequence:
                                  - service: scene.turn_on
                                    target:
                                      entity_id: !input scene_single_left
                          - service: >
                              {% if states('scene_single_left') not in ['unknown',''] %}
                              scene.turn_on
                              {% endif %}
                              # Pokud scéna není nastavena, neprovádí se
                            data: {}
                            target:
                              entity_id: !input scene_single_left
                          - parallel:
                            - sequence: !input single_click_action_left

                      - conditions: "{{ click_count == 2 }}"
                        sequence:
                          - choose:
                              - conditions:
                                  - condition: template
                                    value_template: "{{ states('scene_double_left') not in ['unknown',''] }}"
                                sequence:
                                  - service: scene.turn_on
                                    target:
                                      entity_id: !input scene_double_left
                          - parallel:
                            - sequence: !input double_click_action_left

                      - conditions: "{{ click_count == 3 }}"
                        sequence:
                          - choose:
                              - conditions:
                                  - condition: template
                                    value_template: "{{ states('scene_triple_left') not in ['unknown',''] }}"
                                sequence:
                                  - service: scene.turn_on
                                    target:
                                      entity_id: !input scene_triple_left
                          - parallel:
                            - sequence: !input triple_click_action_left

              - conditions:
                  - condition: template
                    value_template: "{{ this_button == 'right' }}"
                sequence:
                  - choose:
                      - conditions: "{{ click_count == 1 }}"
                        sequence:
                          - choose:
                              - conditions:
                                  - condition: template
                                    value_template: "{{ states('scene_single_right') not in ['unknown',''] }}"
                                sequence:
                                  - service: scene.turn_on
                                    target:
                                      entity_id: !input scene_single_right
                          - parallel:
                            - sequence: !input single_click_action_right

                      - conditions: "{{ click_count == 2 }}"
                        sequence:
                          - choose:
                              - conditions:
                                  - condition: template
                                    value_template: "{{ states('scene_double_right') not in ['unknown',''] }}"
                                sequence:
                                  - service: scene.turn_on
                                    target:
                                      entity_id: !input scene_double_right
                          - parallel:
                            - sequence: !input double_click_action_right

                      - conditions: "{{ click_count == 3 }}"
                        sequence:
                          - choose:
                              - conditions:
                                  - condition: template
                                    value_template: "{{ states('scene_triple_right') not in ['unknown',''] }}"
                                sequence:
                                  - service: scene.turn_on
                                    target:
                                      entity_id: !input scene_triple_right
                          - parallel:
                            - sequence: !input triple_click_action_right
    default: []
mode: restart
